"""First migration

Revision ID: 39245ad97737
Revises: 
Create Date: 2026-06-16 00:31:37.041467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39245ad97737'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('number', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_index('ix_orders_status', 'orders', ['status'], unique=False)
    op.create_table('sensors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=15), nullable=False),
    sa.Column('channel', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("code ~ '^([0-9]{1,3}\\.){3}[0-9]{1,3}$'", name='ck_sensors_code_ipv4_format'),
    sa.CheckConstraint('channel >= 1 AND channel <= 3', name='ck_sensors_channel_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'channel', name='uq_sensors_code_channel')
    )
    op.create_index('ix_sensors_code_channel', 'sensors', ['code', 'channel'], unique=False)
    op.create_table('units',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('symbol')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('hashed_password', sa.Text(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('workstations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('operation_types',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('items',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('unit_id', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sensor_values',
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('sensor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ts', 'sensor_id')
    )
    op.create_index('ix_sensor_values_sensor_id', 'sensor_values', ['sensor_id'], unique=False)
    op.create_index('ix_sensor_values_ts', 'sensor_values', ['ts'], unique=False)
    op.create_table('user_workstations',
    sa.Column('workstation_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workstation_id'], ['workstations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workstation_id', 'user_id')
    )
    op.create_table('resource_specifications',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('operation_type_id', sa.BigInteger(), nullable=False),
    sa.Column('workstation_id', sa.BigInteger(), nullable=False),
    sa.Column('output_quantity', sa.Integer(), nullable=False),
    sa.CheckConstraint('output_quantity >= 1', name='ck_resource_specifications_output_quantity_positive'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operation_type_id'], ['operation_types.id'], ),
    sa.ForeignKeyConstraint(['workstation_id'], ['workstations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', name='uq_resource_specifications_item_id')
    )
    op.create_index('ix_resource_specifications_item_id', 'resource_specifications', ['item_id'], unique=False)
    op.create_index('ix_resource_specifications_operation_type_id', 'resource_specifications', ['operation_type_id'], unique=False)
    op.create_index('ix_resource_specifications_workstation_id', 'resource_specifications', ['workstation_id'], unique=False)
    op.create_table('resource_specification_inputs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('resource_specification_id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_resource_specification_inputs_quantity_positive'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['resource_specification_id'], ['resource_specifications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_resource_specification_inputs_item_id', 'resource_specification_inputs', ['item_id'], unique=False)
    op.create_index('ix_resource_specification_inputs_resource_specification_id', 'resource_specification_inputs', ['resource_specification_id'], unique=False)
    op.create_table('order_lines',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_order_lines_quantity_positive'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_order_lines_item_id', 'order_lines', ['item_id'], unique=False)
    op.create_index('ix_order_lines_order_id', 'order_lines', ['order_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('task_type', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('planned_quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('actual_quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('defect_quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('order_line_id', sa.BigInteger(), nullable=False),
    sa.Column('resource_specification_id', sa.BigInteger(), nullable=True),
    sa.Column('workstation_id', sa.BigInteger(), nullable=True),
    sa.Column('source_workstation_id', sa.BigInteger(), nullable=True),
    sa.Column('target_workstation_id', sa.BigInteger(), nullable=True),
    sa.Column('executor_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['executor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_line_id'], ['order_lines.id'], ),
    sa.ForeignKeyConstraint(['resource_specification_id'], ['resource_specifications.id'], ),
    sa.ForeignKeyConstraint(['source_workstation_id'], ['workstations.id'], ),
    sa.ForeignKeyConstraint(['target_workstation_id'], ['workstations.id'], ),
    sa.ForeignKeyConstraint(['workstation_id'], ['workstations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tasks_order_id', 'tasks', ['order_id'], unique=False)
    op.create_index('ix_tasks_order_line_id', 'tasks', ['order_line_id'], unique=False)
    op.create_index('ix_tasks_resource_specification_id', 'tasks', ['resource_specification_id'], unique=False)
    op.create_index('ix_tasks_status', 'tasks', ['status'], unique=False)
    op.create_index('ix_tasks_task_type', 'tasks', ['task_type'], unique=False)
    op.create_index('ix_tasks_workstation_id', 'tasks', ['workstation_id'], unique=False)
    op.create_table('task_dependencies',
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('depends_on_task_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'depends_on_task_id')
    )
    op.create_table('task_history',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('changed_by_id', sa.Integer(), nullable=False),
    sa.Column('old_status', sa.Text(), nullable=False),
    sa.Column('new_status', sa.Text(), nullable=False),
    sa.Column('actual_quantity_delta', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('defect_quantity_delta', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('actual_quantity_delta IS NULL OR actual_quantity_delta >= 0', name='ck_task_history_actual_quantity_delta_non_negative'),
    sa.CheckConstraint('defect_quantity_delta IS NULL OR defect_quantity_delta >= 0', name='ck_task_history_defect_quantity_delta_non_negative'),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_task_history_new_status', 'task_history', ['new_status'], unique=False)
    op.create_index('ix_task_history_task_id_created_at', 'task_history', ['task_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_task_history_task_id_created_at', table_name='task_history')
    op.drop_index('ix_task_history_new_status', table_name='task_history')
    op.drop_table('task_history')
    op.drop_table('task_dependencies')
    op.drop_index('ix_tasks_workstation_id', table_name='tasks')
    op.drop_index('ix_tasks_task_type', table_name='tasks')
    op.drop_index('ix_tasks_status', table_name='tasks')
    op.drop_index('ix_tasks_resource_specification_id', table_name='tasks')
    op.drop_index('ix_tasks_order_line_id', table_name='tasks')
    op.drop_index('ix_tasks_order_id', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('ix_order_lines_order_id', table_name='order_lines')
    op.drop_index('ix_order_lines_item_id', table_name='order_lines')
    op.drop_table('order_lines')
    op.drop_index('ix_resource_specification_inputs_resource_specification_id', table_name='resource_specification_inputs')
    op.drop_index('ix_resource_specification_inputs_item_id', table_name='resource_specification_inputs')
    op.drop_table('resource_specification_inputs')
    op.drop_index('ix_resource_specifications_workstation_id', table_name='resource_specifications')
    op.drop_index('ix_resource_specifications_operation_type_id', table_name='resource_specifications')
    op.drop_index('ix_resource_specifications_item_id', table_name='resource_specifications')
    op.drop_table('resource_specifications')
    op.drop_table('user_workstations')
    op.drop_index('ix_sensor_values_ts', table_name='sensor_values')
    op.drop_index('ix_sensor_values_sensor_id', table_name='sensor_values')
    op.drop_table('sensor_values')
    op.drop_table('items')
    op.drop_table('operation_types')
    op.drop_table('workstations')
    op.drop_table('users')
    op.drop_table('units')
    op.drop_index('ix_sensors_code_channel', table_name='sensors')
    op.drop_table('sensors')
    op.drop_index('ix_orders_status', table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
