"""First migration

Revision ID: 39245ad97737
Revises: 
Create Date: 2026-06-16 00:31:37.041467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39245ad97737'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('number', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_index('ix_orders_status', 'orders', ['status'], unique=False)
    op.create_table('sensors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=15), nullable=False),
    sa.Column('channel', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("code ~ '^([0-9]{1,3}\\.){3}[0-9]{1,3}$'", name='ck_sensors_code_ipv4_format'),
    sa.CheckConstraint('channel >= 1 AND channel <= 3', name='ck_sensors_channel_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'channel', name='uq_sensors_code_channel')
    )
    op.create_index('ix_sensors_code_channel', 'sensors', ['code', 'channel'], unique=False)
    op.create_table('units',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('symbol')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('hashed_password', sa.Text(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('work_centers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('items',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('unit_id', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_items_name', 'items', ['name'], unique=False)
    op.create_table('sensor_values',
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('sensor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ts', 'sensor_id')
    )
    op.create_index('ix_sensor_values_sensor_id', 'sensor_values', ['sensor_id'], unique=False)
    op.create_index('ix_sensor_values_ts', 'sensor_values', ['ts'], unique=False)
    op.create_table('user_work_centers',
    sa.Column('work_center_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_center_id'], ['work_centers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('work_center_id', 'user_id')
    )
    op.create_table('boms',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('version', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'version', name='uq_boms_item_id_version')
    )
    op.create_index('ix_boms_is_default', 'boms', ['is_default'], unique=False)
    op.create_index('ix_boms_item_id', 'boms', ['item_id'], unique=False)
    op.create_index('ix_boms_status', 'boms', ['status'], unique=False)
    op.create_table('routes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('version', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'version', name='uq_routes_item_id_version')
    )
    op.create_index('ix_routes_is_default', 'routes', ['is_default'], unique=False)
    op.create_index('ix_routes_item_id', 'routes', ['item_id'], unique=False)
    op.create_index('ix_routes_status', 'routes', ['status'], unique=False)
    op.create_table('bom_lines',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('bom_id', sa.BigInteger(), nullable=False),
    sa.Column('component_item_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('scrap_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_bom_lines_quantity_positive'),
    sa.CheckConstraint('scrap_percent >= 0 AND scrap_percent <= 100', name='ck_bom_lines_scrap_percent_range'),
    sa.ForeignKeyConstraint(['bom_id'], ['boms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['component_item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bom_lines_bom_id', 'bom_lines', ['bom_id'], unique=False)
    op.create_index('ix_bom_lines_component_item_id', 'bom_lines', ['component_item_id'], unique=False)
    op.create_table('order_lines',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('bom_id', sa.BigInteger(), nullable=True),
    sa.Column('route_id', sa.BigInteger(), nullable=True),
    sa.CheckConstraint('quantity > 0', name='ck_order_lines_quantity_positive'),
    sa.ForeignKeyConstraint(['bom_id'], ['boms.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_order_lines_bom_id', 'order_lines', ['bom_id'], unique=False)
    op.create_index('ix_order_lines_item_id', 'order_lines', ['item_id'], unique=False)
    op.create_index('ix_order_lines_order_id', 'order_lines', ['order_id'], unique=False)
    op.create_index('ix_order_lines_route_id', 'order_lines', ['route_id'], unique=False)
    op.create_table('route_operations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('route_id', sa.BigInteger(), nullable=False),
    sa.Column('operation_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('work_center_id', sa.BigInteger(), nullable=False),
    sa.Column('setup_time_minutes', sa.Integer(), nullable=False),
    sa.Column('run_time_minutes', sa.Integer(), nullable=False),
    sa.Column('requires_quality_review', sa.Boolean(), nullable=False),
    sa.CheckConstraint('run_time_minutes >= 0', name='ck_route_operations_run_time_minutes_non_negative'),
    sa.CheckConstraint('setup_time_minutes >= 0', name='ck_route_operations_setup_time_minutes_non_negative'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_center_id'], ['work_centers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('route_id', 'operation_number', name='uq_route_operations_route_id_operation_number')
    )
    op.create_index('ix_route_operations_route_id', 'route_operations', ['route_id'], unique=False)
    op.create_index('ix_route_operations_work_center_id', 'route_operations', ['work_center_id'], unique=False)
    op.create_table('operation_inputs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('operation_id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_operation_inputs_quantity_positive'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['operation_id'], ['route_operations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_operation_inputs_item_id', 'operation_inputs', ['item_id'], unique=False)
    op.create_index('ix_operation_inputs_operation_id', 'operation_inputs', ['operation_id'], unique=False)
    op.create_table('operation_outputs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('operation_id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_operation_outputs_quantity_positive'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['operation_id'], ['route_operations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_operation_outputs_item_id', 'operation_outputs', ['item_id'], unique=False)
    op.create_index('ix_operation_outputs_operation_id', 'operation_outputs', ['operation_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('task_type', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('planned_quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('actual_quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('defect_quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('order_line_id', sa.BigInteger(), nullable=False),
    sa.Column('route_operation_id', sa.BigInteger(), nullable=True),
    sa.Column('work_center_id', sa.BigInteger(), nullable=True),
    sa.Column('source_work_center_id', sa.BigInteger(), nullable=True),
    sa.Column('target_work_center_id', sa.BigInteger(), nullable=True),
    sa.Column('executor_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['executor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_line_id'], ['order_lines.id'], ),
    sa.ForeignKeyConstraint(['route_operation_id'], ['route_operations.id'], ),
    sa.ForeignKeyConstraint(['source_work_center_id'], ['work_centers.id'], ),
    sa.ForeignKeyConstraint(['target_work_center_id'], ['work_centers.id'], ),
    sa.ForeignKeyConstraint(['work_center_id'], ['work_centers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tasks_order_id', 'tasks', ['order_id'], unique=False)
    op.create_index('ix_tasks_order_line_id', 'tasks', ['order_line_id'], unique=False)
    op.create_index('ix_tasks_status', 'tasks', ['status'], unique=False)
    op.create_index('ix_tasks_task_type', 'tasks', ['task_type'], unique=False)
    op.create_index('ix_tasks_work_center_id', 'tasks', ['work_center_id'], unique=False)
    op.create_table('task_dependencies',
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('depends_on_task_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'depends_on_task_id')
    )
    op.create_table('task_history',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('changed_by_id', sa.Integer(), nullable=False),
    sa.Column('old_status', sa.Text(), nullable=False),
    sa.Column('new_status', sa.Text(), nullable=False),
    sa.Column('actual_quantity_delta', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('defect_quantity_delta', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('actual_quantity_delta IS NULL OR actual_quantity_delta >= 0', name='ck_task_history_actual_quantity_delta_non_negative'),
    sa.CheckConstraint('defect_quantity_delta IS NULL OR defect_quantity_delta >= 0', name='ck_task_history_defect_quantity_delta_non_negative'),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_task_history_new_status', 'task_history', ['new_status'], unique=False)
    op.create_index('ix_task_history_task_id_created_at', 'task_history', ['task_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_task_history_task_id_created_at', table_name='task_history')
    op.drop_index('ix_task_history_new_status', table_name='task_history')
    op.drop_table('task_history')
    op.drop_table('task_dependencies')
    op.drop_index('ix_tasks_work_center_id', table_name='tasks')
    op.drop_index('ix_tasks_task_type', table_name='tasks')
    op.drop_index('ix_tasks_status', table_name='tasks')
    op.drop_index('ix_tasks_order_line_id', table_name='tasks')
    op.drop_index('ix_tasks_order_id', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('ix_operation_outputs_operation_id', table_name='operation_outputs')
    op.drop_index('ix_operation_outputs_item_id', table_name='operation_outputs')
    op.drop_table('operation_outputs')
    op.drop_index('ix_operation_inputs_operation_id', table_name='operation_inputs')
    op.drop_index('ix_operation_inputs_item_id', table_name='operation_inputs')
    op.drop_table('operation_inputs')
    op.drop_index('ix_route_operations_work_center_id', table_name='route_operations')
    op.drop_index('ix_route_operations_route_id', table_name='route_operations')
    op.drop_table('route_operations')
    op.drop_index('ix_order_lines_route_id', table_name='order_lines')
    op.drop_index('ix_order_lines_order_id', table_name='order_lines')
    op.drop_index('ix_order_lines_item_id', table_name='order_lines')
    op.drop_index('ix_order_lines_bom_id', table_name='order_lines')
    op.drop_table('order_lines')
    op.drop_index('ix_bom_lines_component_item_id', table_name='bom_lines')
    op.drop_index('ix_bom_lines_bom_id', table_name='bom_lines')
    op.drop_table('bom_lines')
    op.drop_index('ix_routes_status', table_name='routes')
    op.drop_index('ix_routes_item_id', table_name='routes')
    op.drop_index('ix_routes_is_default', table_name='routes')
    op.drop_table('routes')
    op.drop_index('ix_boms_status', table_name='boms')
    op.drop_index('ix_boms_item_id', table_name='boms')
    op.drop_index('ix_boms_is_default', table_name='boms')
    op.drop_table('boms')
    op.drop_table('user_work_centers')
    op.drop_index('ix_sensor_values_ts', table_name='sensor_values')
    op.drop_index('ix_sensor_values_sensor_id', table_name='sensor_values')
    op.drop_table('sensor_values')
    op.drop_index('ix_items_name', table_name='items')
    op.drop_table('items')
    op.drop_table('work_centers')
    op.drop_table('users')
    op.drop_table('units')
    op.drop_index('ix_sensors_code_channel', table_name='sensors')
    op.drop_table('sensors')
    op.drop_index('ix_orders_status', table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
