import { demoItems, demoWorkCenters } from "@/entities/catalog/mock";
import type { TaskDto } from "./types";

export const demoTasks: TaskDto[] = [
  {
    id: 1,
    task_type: "operation",
    status: "to_do",
    description: "Экструзия",
    planned_quantity: "100.000000",
    actual_quantity: "0.000000",
    defect_quantity: "0.000000",
    order_id: 1,
    order_line_id: 1,
    item_id: 100,
    route_operation_id: 12,
    work_center_id: 1,
    source_work_center_id: null,
    target_work_center_id: null,
    item: { id: 100, name: "Кабель 3x2.5", unit_id: 1 },
    work_center: demoWorkCenters[0],
    source_work_center: null,
    target_work_center: null,
    executor_id: null,
    created_at: "2026-06-15T10:00:00Z",
    updated_at: "2026-06-15T10:00:00Z",
  },
  {
    id: 2,
    task_type: "warehouse_delivery",
    status: "in_progress",
    description: "Доставка материала",
    planned_quantity: "300.000000",
    actual_quantity: "0.000000",
    defect_quantity: "0.000000",
    order_id: 1,
    order_line_id: 1,
    item_id: 10,
    route_operation_id: null,
    work_center_id: null,
    source_work_center_id: 2,
    target_work_center_id: 1,
    item: { id: demoItems[0].id, name: demoItems[0].name, unit_id: demoItems[0].unit_id },
    work_center: null,
    source_work_center: demoWorkCenters[1],
    target_work_center: demoWorkCenters[0],
    executor_id: 8,
    created_at: "2026-06-15T10:02:00Z",
    updated_at: "2026-06-15T10:04:00Z",
  },
];
